
#SUBDIRS:=
#SRCS:= 
INSTALL_INCS:= event_loop.h tcp_server.h tcp_connection.h tcp_client.h \
	callbacks.h buffer.h inet_address.h endian.h channel.h \
	event_loop_thread_pool.h

include $(TOPDIR)/common.mk
